#!/bin/bash -
###############################################################
## eGW_tcpdump.sh
## version: 3.0
## update：20180503
###############################################################
LOG_PATH=/root/eGW/Logs/tcpdump
MINSIZE=50000000
TIMER=5

while :
do
    DATE_DIR=$(date +%F)
    STIME=$(date +%F"_"%H%M%S)
    if [[ ! -d ${LOG_PATH}/$DATE_DIR  ]];then
        mkdir -p ${LOG_PATH}/$DATE_DIR
    fi

    DUMP_PID=$(ps -ef | grep "tcpdump -i any sctp or port 4500" | grep pcap | awk '{print $2}')
    if [[ ! $DUMP_PID ]];then
        tcpdump -i any sctp or port 4500 -s 0 -w ${LOG_PATH}/${DATE_DIR}/${STIME}.pcap &
        DUMP_PID=$(ps -ef | grep "tcpdump -i any sctp or port 4500" | grep pcap | awk '{print $2}')
    fi

    sleep 1

    PACKSIZE=$(ls -l ${LOG_PATH}/$DATE_DIR | grep ${STIME}.pcap | awk '{print $5}')
    while [[ $PACKSIZE -lt $MINSIZE  ]];
    do
        sleep $TIMER
        PACKSIZE=$(ls -l ${LOG_PATH}/$DATE_DIR | grep ${STIME}.pcap | awk '{print $5}')
    done

    kill -9 $DUMP_PID

    ETIME=$(date +%H%M%S)
    mv ${LOG_PATH}/${DATE_DIR}/${STIME}.pcap ${LOG_PATH}/${DATE_DIR}/${STIME}-${ETIME}.pcap
	
    ls -lt $LOG_PATH/$DATE_DIR/* | awk '{if(NR>2){print $9}}' | xargs gzip &
    ls -lt $LOG_PATH/${DATE_DIR}/*.gz | awk '{if(NR>20){print $9}}' | xargs rm -rf &
    ls -lt $LOG_PATH | awk '{if(NR>5){print $9}}' | xargs rm -rf &
done


